port: 4000
authsecret: "XXXXXX"
debugmode: true
alchemyapikey: "XXXXXXXXXXXXXXXXXX"
l1signerprivatekey: "XXXXXXXXXXXXXXXXXX"
starkprivatekey: "XXXXXXXXXXXXXXXXXX"
dsn: "host=localhost user=postgres password=postgres dbname=nft port=5432 sslmode=disable"